### ISSUE TITLE
is there any usage method

### ISSUE THREAD

**Issue by bau720123** [normanhh3/jqm-iscroll#2]
hi @normanhh3 
is there any usage method ?
I haven't see any demo page

**Comment by normanhh3** [comment]
Unfortunately see #1 for the current status.  I need to get a fix in.  To answer your question, the code is designed to be demoed with the (MeteorJS platform)[http://www.meteor.com].

A little bit of wrangling and it could be demoed with another tool.

I need to merge in changes from my other work for it to be back into a proper working state.
